version: "{build}"

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "REDasm_Windows_i686_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"

environment:
  build_repo: REDasm-Builds
  github_token:
    secure: 1xDbJm4/ZdjBTgkbzAHDtNOcsRwJz4u1GSfI4UEA2ZQYt1zFWURWu9+gyy9rEGck

skip_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - mkdir build
  - xcopy database build\database /E
  - cd build
  - qmake CONFIG+=release ..
  - mingw32-make -j4
  - ps: ../ci/package.ps1
  - ps: ../ci/deploy.ps1