name: REDasm Builds

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: Linux (Ubuntu 20.04 LTS)

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-10 g++-10 qt5-default libqt5x11extras5-dev cmake
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
        git submodule update --init --recursive

    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
        make -j4
        make install DESTDIR=$PWD/AppDir

    - name: Prepare AppImage
      shell: bash
      run: |
        cd build
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod +x linuxdeploy*.AppImage
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        cp ../REDasm.desktop AppDir/usr/share/applications/
        cp ../res/logo.png AppDir/usr/share/icons/hicolor/256x256/apps/redasm.png
        
    - name: Generate AppImage
      run: |
        cd build
        LD_LIBRARY_PATH=$PWD/AppDir/usr/lib/x86_64-linux-gnu ./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt --output appimage
        mv REDasm-*.AppImage REDasm_Linux_AMD64_`date +%Y%m%d`.AppImage
        
    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: Linux (AppImage)
        path: build/REDasm*.AppImage
        if-no-files-found: error
        
  windows:
    runs-on: windows-latest
    name: Windows

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.12.1
 
      - name: Build
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          cmake --build . -j4 --config Release
          cmake --build . --target REDasmDeploy
          
      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: Windows (Portable)
          path: build/deploy
          if-no-files-found: error
